spring:
  threads:
    virtual:
      enabled: true
  cloud:
    open-feign:
      httpclient:
        disable-ssl-validation: true
        enabled: false
      okhttp:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 30000
            loggerLevel: full

star-wars:
  url: https://swapi.dev/api
  character:
    url: ${star-wars.url}/people
  film:
    url: ${star-wars.url}/films

springdoc:
  api-docs:
    path: /swagger
  swagger-ui:
    path: /swagger-ui

resilience4j:
  # configuração do time limiter
  timelimiter:
    configs:
      default:
        timeoutDuration: 7s # tempo limite para completar uma requisição
        cancelRunningFuture: true # caso passe do tempo acima ele cancela a execuçãoda thread
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5 # número de requisições para medir a taxa de erro nas chamadas últimas chamadas realizadas /// Ex: Pega as últimas 5 chamadas feitas ao serviço externo e calcula a taxa de falhas
        minimumNumberOfCalls: 2 # número mínimo de chamadas antes de abrir/fechar o circuito
        permittedNumberOfCallsInHalfOpenState: 2 # número permitido de chamadas no estado meio aberto
        waitDurationInOpenState: 10s # informa a quantidade de tempo que o circuit breaker ficará no estado "Open" antes de mudar para "Half-Open"
        failureRateThreshold: 50 # informa o limite de taxa de falha, em procentagem(%), que aciona a abertura do circuit breaker, ou seja, muda para o estado "Open" ///Ex: para abrir o circuito é necessário 50% de falha
        recordExceptions:
          # indica quais exceções que podem abrir o circuito
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException

management:
  endpoints:
    web:
      exposure:
        include: '*' # expondo todos os endpoints disponíveis do Spring Actuator
  endpoint:
    health:
      show-details: always