star-wars:
  url: https://swapi.dev/api
  character:
    url: ${star-wars.url}/people
  film:
    url: ${star-wars.url}/films

springdoc:
  api-docs:
    path: /swagger
  swagger-ui:
    path: /swagger-ui

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 7s
        cancelRunningFuture: true